### ISSUE TITLE
I get the following error after form submission.

### ISSUE THREAD

**Issue by con322** [kartik-v/yii2-widget-fileinput#10]
Using the yii2 advanced template improved & using MAMP.

I get the following error when submitting the default signup form with the upload field.

    Integrity constraint violation – yii\db\IntegrityException

    SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'avatar' cannot be null
    The SQL being executed was: INSERT INTO `user` (`username`, `email`, `password_hash`,     `auth_key`, `status`, `avatar`, `created_at`, `updated_at`) VALUES ('fgdfgdfgdf', 'con322@fdfgdfgfd.com',     '$2y$13$NkYSCZbzk/pNlWDutTR0t.yKmwtebx7F0DbiR1Uzviw3NNneNrJAi', '    TzVPxoPxiW5OLuMinKZ0bH7baK0VNPJ6', 10, NULL, 1422215977, 1422215977)

**Comment by kartik-v** [comment]
This is not related to this extension. As stated in the error message, you need to check your code that is not populating data into the field named `avatar` which is constrained to NOT NULL in your db design.
