### ISSUE TITLE
$_FILES Empty after error

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-widget-fileinput#100]
$_FILES is empty on the following case:
1) When I select a file which generates a too large error
2) I upload another file that is correct
3) There are 2 files in the preview
4) I remove the first (too large)
5) press upload...
Now I get $_FILES which is just empty, the correct document is not even uploaded.

When I reload the page , just select the correct document and upload... then everything is uploaded correctly

**Comment by ScreamieGitHub** [comment]
I have the same issue in another situation. 

When the widget adds more files than allowed in maxFiles, an error occurs. If you delete additional files, the error will disappear, but $ _FILES will be empty.

**Comment by RomanBush** [comment]
I have this bug in version 1.1.1.
1. In Yii2:

```
<?=  $form->field($model, 'img_slide[]')->widget(FileInput::class, [
 'options'       => [
                        'accept'   => 'image/*',
                        'multiple' => true,
                    ],

```

and some another options, including "uploadUrl", "showUpload" => true and so on.


2. On preview page I add some files (two or more).

3. On preview page I click on "trash" button at the file, so remove one file.

4. On submit page I receive empty $_FILES.

If I dont click on trash button - all be okey, $_FILES contain all files, which I add to preview page.
