### ISSUE TITLE
Upload file return null?

### ISSUE THREAD

**Issue by za4me** [kartik-v/yii2-widget-fileinput#102]
Hi, help me please, why i use `UploadedFile::getInstance` and him return null?

In view i use this code:
`<?= $form->field($model, 'image')->widget(\kartik\file\FileInput::class, []) ?>`

In controller i write this:
`$image = UploadedFile::getInstance($model, 'image');`

And `$image = null;` after choice file.

Thanks.

**Comment by za4me** [comment]
If i use fileInput in my view, i get `$_FILES` array. But if i use `widget(FileInput::class, [])` i don't get it.

**Comment by gpl2017** [comment]
Hi,i think maybe as follows in the controller file:
$model->image = UploadedFile::getInstance($model, 'image');

2017-02-22 

liuguiping_monitor 



发件人：Boris Yakushev <notifications@github.com>
发送时间：2017-02-21 21:05
主题：[kartik-v/yii2-widget-fileinput] Upload file return null? (#102)
收件人："kartik-v/yii2-widget-fileinput"<yii2-widget-fileinput@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Hi, help me please, why i use UploadedFile::getInstance and him return null?
In view i use this code:
<?= $form->field($model, 'image')->widget(\kartik\file\FileInput::class, []) ?>
In controller i write this:
$image = UploadedFile::getInstance($model, 'image');
And $image = null; after choice file.
Thanks.

**Comment by za4me** [comment]
Nope. Form don't get me file becouse i don't use `'enctype' => 'multipart/form-data'` in ActiveForm.
