### ISSUE TITLE
Individual select not uploading all

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-widget-fileinput#103]
When I select 3 files at once and press upload everything works, the preview show all 3 files and when I press upload, all are uploade

When I select 1, press ok, then select anotherone and press ok, and select the 3rd and press ok, then I have 3 files in the preview window. When I then press uplaod, only hte last file is uploaded

**Comment by artemzakholodilo** [comment]
+1

**Comment by kartik-v** [comment]
The scenario you mentioned will only work if you are using AJAX uploads and you should not be reading the file input in your server code via FORM based submission.

Read the modes of [usage of the plugin](http://plugins.krajee.com/file-input#usage-modes). You should not be trying to combine the modes else you will face an issue like above.
