### ISSUE TITLE
Bug when using select2 and fileinput together (text files only)

### ISSUE THREAD

**Issue by AndersonDan** [kartik-v/yii2-widget-fileinput#105]
Video demo:

https://www.youtube.com/watch?v=owxlofelVvs

Height of `file-preview-text`

![2](https://cloud.githubusercontent.com/assets/10473169/24082574/a0f8ded2-0ca6-11e7-9ac2-206e0cc44bee.jpg)

**Comment by kartik-v** [comment]
Could not reproduce your issue on my tests. You need to check if you have the latest releases of all the extensions (Select2 and Fileinput and the plugins).

Also you need to check if you have other third party styling, themes, or CSS/JS that could be causing this.

**Comment by AndersonDan** [comment]
Excuse me, I found the mistake.

![1](https://cloud.githubusercontent.com/assets/10473169/24220835/abe8c22c-0f2a-11e7-9c01-7e8872e00b57.png)
