### ISSUE TITLE
Upgrade bootstrap-fileinput plugin

### ISSUE THREAD

**Issue by tsdogs** [kartik-v/yii2-widget-fileinput#116]
It should be about time to upgrade the bootstrap-fileinput plugin requirement in the composer.json (4.3 or 4.4)

There are enhancements which are not available (i.e. layoutTemplate).

**Comment by kartik-v** [comment]
You should be able to get the updated code automatically via composer - the dependency is `~4.2` 

so all versions between `4.2` and `5.0` will be auto updated.

**Comment by tsdogs** [comment]
ok sorry I did get 4.3.9, though for some reasons I wasn't able to use layoutTemplate. I thought it was related to the 4.2 version specified in the composer.json (missed the ~)
