### ISSUE TITLE
The plugin breaks when it is rebooted using PJAX

### ISSUE THREAD

**Issue by alexg0mel** [kartik-v/yii2-widget-fileinput#119]
Greetings. The plugin (events) breaks if I overload the container in which the widget is located. (This is necessary if I want to upload photos from the social network, so they appeared in the preview.)

Or can I somehow "tell" the widget in js, that there are new previews?

russian:   Приветствую. Ломается плагин (события) если я перегружаю контейнер в котором находится виджет.  (Это надо если я хочу подгрузить фото из соцсети, чтобы они появились в превью.)

Или можно как нибудь "сказать" виджету в js, что появились новые превью?

**Comment by kartik-v** [comment]
Use the plugin's [refresh method](http://plugins.krajee.com/file-input#method-refresh) with updated `initialPreview` and `initialPreviewConfig`.

Or use [destroy method]](http://plugins.krajee.com/file-input#method-destroy) and reinitialize the plugin with updated `initialPreview` and `initialPreviewConfig`.
