### ISSUE TITLE
How to remove not uploaded yet icon in preview of image

### ISSUE THREAD

**Issue by creotech** [kartik-v/yii2-widget-fileinput#128]
Hi Karthik,

Please tell me How to remove not uploaded yet icon in preview  image(already uploaded thing)
![screenshot 15](https://user-images.githubusercontent.com/30858527/34256217-475e0e5c-e67a-11e7-9112-c4836830cd18.png)

**Comment by kartik-v** [comment]
Set the `indicatorNew` and `indicatorNewTitle` to an empty string within [fileActionSettings](http://plugins.krajee.com/file-input/plugin-options#fileActionSettings).
