### ISSUE TITLE
uploadExtraData怎么使用Function？

### ISSUE THREAD

**Issue by chenchao123** [kartik-v/yii2-widget-fileinput#129]
uploadExtraData 怎么使用function?
echo $form->field($model, 'banner[]')->label('banner图')->widget(FileInput::classname(), [
        'options' => ['multiple' => true],
        'pluginOptions' => [
            // 需要预览的文件格式
            'previewFileType' => 'image',
            // 预览的文件
            'initialPreview' => [],
            // 需要展示的图片设置，比如图片的宽度等
            'initialPreviewConfig' => [],
            // 是否展示预览图
            'initialPreviewAsData' => true,
            // 异步上传的接口地址设置
            'uploadUrl' => Url::toRoute(['/goods/async-banner']),
            // 异步上传需要携带的其他参数，比如商品id等
            //'uploadExtraData' => [
            //    'goods_id' => 1,
            //],
            'uploadExtraData' => "function(){ var obj = {}; obj.fodder = fodderType(); console.log(obj); return obj; } ", // ,

这样设置提示错误：
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in {function(){ var obj = {}; obj.fodder = fodderType(); console.log(obj); return obj;}}

**Comment by muet84** [comment]
had you found solution??
