### ISSUE TITLE
web server must be configured to allow the uploadPath access

### ISSUE THREAD

**Issue by con322** [kartik-v/yii2-widget-fileinput#13]
Not an issue just a bit of guidance. (using MAMP & Yii2 improved advanced template.

I can't access the file due to the default advanced template having a 404 redirect on the _protected directory.

However I don't want to remove the redirect as I know you shouldn't need plus it's not secure and makes image src look horrible.

I see you have the following sentence in your web tip "Note your web server must be configured to allow the uploadPath access."

However I am unsure on what this mean in terms, of what files need editing, what code needs adding. Is it a htaccess thing? Or something that can be done with app config, or assets config?

**Comment by kartik-v** [comment]
Its a simple message stating that your image/uploaded file source must be accessible through a web url (e.g. using img src attribute).
