### ISSUE TITLE
Multiple file upload strange behavior when adding a new file.

### ISSUE THREAD

**Issue by adummy832** [kartik-v/yii2-widget-fileinput#130]
Hi, @kartik-v , The yii2-widget-fileinput works fine when I selected and uploaded multiple files at once also single file upload works well, However I've noticed something strange.

Use case:
1. When the user selected multiple files = (Renders correctly).
2. The user added another file. = (Renders correctly).
PS. I've set ``'overwriteInitial' => false``

However, when I started working on my controller and catch the ``files[]`` attribute which contains the uploaded files. It only contains the latest file in Use Case 2. The files supposedly on Use Case 1 should be contained in the ``files[]`` attribute, But for some reason it is not doing so.

Here is my code for catching the files:
``$mFiles = UploadedFile::getInstances($model, 'files');``

I've also noticed this behavior in the documentation ``http://demos.krajee.com/widget-details/fileinput``
In section FileInput Basic Usage, ex number 2: Add attachments

Do you have any idea, what's causing this also how to resolve this issue?
I've been on this for hours now. Thank you very much.

**Comment by kartik-v** [comment]
I am not sure of how you have configured the input, and the plugin... but it seems you may have to check both of them properly. You may want to read the [usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes) and hope you are not trying to combine the modes as mentioned in the docs.

**Comment by HenryVolkmer** [comment]
it is possible, that in usecase with DetailView, the attribute-name is not in html array notation (trailing "[ ]").
I suggest to append the trailing brackets in FileInput itself.
Please have a look at my PR.
