### ISSUE TITLE
NEED HELP : Multiupload initialPreviewConfig json data from controller seems doesnt work .

### ISSUE THREAD

**Issue by Hallaz** [kartik-v/yii2-widget-fileinput#131]
## Prerequisites

- I have model for image as simple as

        return [
            'id' => 'ID',
            'parent_id' => 'Parent ID',
            'photo' => 'Photo', <= just for filename
        ];
- the case is
       Create Parent model then save then redirect to form for uploading images related to its parent.
- all uploading function work proprerly but no with delete function

this is my upload image form

	echo FileInput::widget([
		'model' => $photo,
		'attribute' => 'photo',
		'options'=>[
			'accept'=>'image/*',
			'multiple'=>true
		],
		'pluginOptions' => [
			'uploadUrl' => Url::to(['/controller/upload', 'id'=> $parent->id]),
			'initialPreview'=>$pre-initViews-data,
			'initialPreviewAsData'=>true,
			'initialCaption'=>"Foto Tersangka",
			'initialPreviewConfig' => $pre-initConfigs-data,
			'overwriteInitial'=>true, 
			//'deleteUrl'=> Url::to(['/controller/deletephoto']),    <= case 2
			'showPreview' => true,
			'showRemove' => false,
			'showUpload' => false,
			'maxFileSize'=>2800
		],
		'pluginEvents' => [
			'fileuploaded'=>"function(event, data, previewId, index){
				console.log(data);
			}",
		]
	]);

- and here my controller side

        $imageFile = UploadedFile::getInstance($model, 'photo');

        $directory = Yii::$app->basePath. '/images/';
        if ($imageFile) {
            $fileName = Yii::$app->security->generateRandomString(). '.' . $imageFile->extension;
            $filePath = $directory . $fileName;
            if ($imageFile->saveAs($filePath) && $model->save(false)) {
                $path = '/images/temp/' . $fileName;
                Image::thumbnail($directory.$fileName, 120, 120)
                ->save(Yii::$app->basePath.$path, ['quality' => 80]);

                $response = [];
                $reponse['initialPreview'] = \Yii::$app->request->BaseUrl.'/images/'.$fileName;
                $reponse['initialPreviewConfig']=[
                    'caption'=>'',
                    'width'=>'90px',
                    'key'=>$model->id,
                    'url'=>Url::to(['/controller/deletephoto']),
                    'extra'=>['id'=>$model->id]
                ];
                echo json_encode($reponse);
            }
        }
And here my json from controller
   {
	"initialPreview": "\/web\/images\/Kl1IJOabLs5ENzzgkuW8ln_TILcDumy9.png",
	"initialPreviewConfig": {
		"caption": "",
		"width": "90px",
		"key": 38,
		"url": "\/web\/index.php?r=controller%2Fdeletephoto",
		"extra": {
			"id": 38
		}
	}
   }    

## Steps to reproduce the issue
- case 1 : withoud pluginOptions => deleteUrl'=> Url::to(['/controller/deletephoto']), 
upload process success, response from controller initialPreview overwriting initial as expected, but initialPreviewConfig seems doesnt fit, so delete button doesnt work/ doesnt give any process when clicked.

- case 2 : with pluginOptions => deleteUrl'=> Url::to(['/controller/deletephoto']) , 
upload process as expected, but when i click delete button post action didnt parse key as below

Query string   
r : controller/deletephoto
Form data 
key : 

## Please review my code, is there somethin wrong?

a huge thanks from me

**Comment by Hallaz** [comment]
after long hours finally i got the way..
replace 

```
          $response = [];
          $reponse['initialPreview'] = \Yii::$app->request->BaseUrl.'/images/'.$fileName;
          $reponse['initialPreviewConfig']=[
              'caption'=>'',
              'width'=>'90px',
              'key'=>$model->id,
              'url'=>Url::to(['/controller/deletephoto']),
              'extra'=>['id'=>$model->id]
          ];
          echo json_encode($reponse);
```



with


                return Json::encode([
                    'initialPreview' =>  \Yii::$app->request->BaseUrl.'/images/'.$fileName,
                    'initialPreviewConfig' => [
                        [
                            'caption'=>'',
                            'width'=>'90px',
                            'key'=>$model->id,
                            'url'=>Url::to(['/controller/deletephoto']),
                            'extra'=>['id'=>$model->id]
                        ],
                    ],
                ]);

dont know why this happen,

**Comment by kartik-v** [comment]
Yes - use Yii's `Json` helper class... it has methods of escaping JS expressions...
