### ISSUE TITLE
Class 'kartik\file\FileInput' not found

### ISSUE THREAD

**Issue by blonder413** [kartik-v/yii2-widget-fileinput#132]
Hi, I try to install in yii2 project from to ways:

`composer require require kartik-v/yii2-widget-fileinput "@dev"`

I have errors

```
[InvalidArgumentException]       
  Could not find package require.  
                                   
  Did you mean one of these?       
      resty/resty                  
      npm-asset/require            
      npm-asset/required           
      npm-asset/requires           
      npm-asset/requireg 
```
Then I used this command

`composer require kartik-v/bootstrap-fileinput "dev-master"`

And the installation was ok, but when I try to use

`use kartik\file\FileInput;`

or

`use kartik\widgets\FileInput`

I have the same error, Class not found

```
Class 'kartik\widgets\FileInput' not found
Class 'kartik\file\FileInput' not found
```

Help me please

**Comment by kartik-v** [comment]
You need to go through composer documentation (you wrongly have typed 2 `require` - there must be only one). Anyway this is not related to this extension.. suggest to post your composer queries in the respective vendor repo or forums... thanks.
