### ISSUE TITLE
fileinput extension Not installed

### ISSUE THREAD

**Issue by hamed2867** [kartik-v/yii2-widget-fileinput#135]
hi.
i tried to install fileinput extension But not fully installed!! and this message was shown to me:
 
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  – Installing kartik-v/bootstrap-fileinput (v4.4.8): Loading from cache
  – Installing kartik-v/yii2-widget-fileinput (dev-master c549564): Cloning c5495641c8
    **Failed to download kartik-v/yii2-widget-fileinput from source: Failed to clone https://github.com/kartik-v/yii2-widget-fileinput.git, git was not found, check that it is installed and in your PATH env.

sh: git: command not found**

 Now trying to download from dist
  – Installing kartik-v/yii2-widget-fileinput (dev-master c549564): Loading from cache
Package mongosoft/yii2-upload-behavior is abandoned, you should avoid using it. Use mohorev/yii2-upload-behavior instead.
Writing lock file
Generating autoload files.
 
 
and when i used this command :

```
echo '<label class="control-label">Add Attachments</label>';
echo FileInput::widget([
    'model' => $model,
    'attribute' => 'attachment_1',
    'options' => ['multiple' => true]
]);
```

this error happend : 

**Class ‘kartik\widgets\FileInput’ not found**
 
can you help me?!

**Comment by kartik-v** [comment]
You do not have a proper composer or git installation on your server - you may want to read the composer documentation and check the pre-requisites for installing composer package manager.

**Comment by crmarin** [comment]
change 
use kartik\widgets\FileInput;
to
use kartik\file\FileInput;
