### ISSUE TITLE
enableAjaxValidation false not working in kartik form builder in yii2

### ISSUE THREAD

**Issue by ajoudeh** [kartik-v/yii2-widget-fileinput#138]
How I can disable  Ajax Validation for file input?

Thanks,

**Comment by kartik-v** [comment]
I am not able to understand what you mean by ajax validation for your case. The `enableAjaxValidation` is a feature of yii2 active form and only works for standard Yii2 validation rules (e.g. required, etc.) implemented for Yii2 Model attributes.

Any other widgets that depend on jquery plugins can have their own inbuilt rules which are totally separate than above like `bootstrap-fileinput` used by `yii2-widget-fileinput`. The plugin has its own validation options to validate the file input - and you would need to control that through `pluginOptions` within 'kartik\file\FileInput`. The `enableAjaxValidation` feature of yii2 active form will have no impact on the `kartik\file\FileInput::pluginOptions`.

**Comment by ajoudeh** [comment]
Thanks for your reply. what I mean is when i enable enableAjaxValidation on ActiveForm options, the file field still give me required validation even i select the file. Code Sample:

` $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data'],
                    'id' => 'individual-stage-two-form',
                    'action' => ['/quote/individual-stage-two', 'refID' => $model->reference_number],
                    'type' => ActiveForm::TYPE_VERTICAL,
                    //'enableAjaxValidation' => true
                ]);
 Form::widget([
                        'model' => $model,
                        'form' => $form,
                        'columns' => 4,
                        'attributes' => [
                            'family_book_file' => [
                                'type' => Form::INPUT_WIDGET,
                                'widgetClass' => \kartik\widgets\FileInput::className(),
                                //'label' => false,
                                'enableClientValidation' => false,
                                'enableAjaxValidation' => false,
                                'columnOptions' => ['colspan' => 2],
                                'options' => [
                                    'pluginOptions' => [
                                        'enableClientValidation' => false,
                                        'enableAjaxValidation' => false,
                                        'maxFileCount' => 1,
                                        'maxFileSize' => 5120,
                                        'showUpload' => false,
                                        'showPreview' => false,
                                        'initialCaption' => $model->getAttributeLabel(''),
                                    ],
                                    'options' => [
                                        'enableClientValidation' => false,
                                        'enableAjaxValidation' => false,
                                        'placeholder' => $model->getAttributeLabel('')
                                    ]
                                ],
                            ],
                        ]
                    ]);`

![img_20180818_195928](https://user-images.githubusercontent.com/1451200/44301551-89720780-a321-11e8-953c-3411e7d1ce15.jpg)

**Comment by kartik-v** [comment]
As I mentioned you are wrongly setting unrelated properties - `enableClientValidation` and  `enableAjaxValidation` within `pluginOptions` - there are no such properties available in `bootstrap-fileinput` plugin. You can [read here what plugin options are supported by `bootstrap-fileinput` plugin](http://plugins.krajee.com/file-input/plugin-options#required).

With regards validation of the model attribute used for the file input within Yii2 - you need to go through yii2 model validation guide and then set the `enableClientValidation` and  `enableAjaxValidation`  properties at the yii2 active form,

**Comment by kartik-v** [comment]
Set `minFileCount` to `0` and `required` to `false` within `pluginOptions` if you want to make the file input optional.
