### ISSUE TITLE
Multiple input field on one form.

### ISSUE THREAD

**Issue by con322** [kartik-v/yii2-widget-fileinput#14]
Is it possible to have multiple upload field on one form as I don't want one field and several files.

Can I have multiple fields but still make use of the current controller function such as upload etc.

**Comment by kartik-v** [comment]
You can choose to do either (either keep one file input and capture using multi upload... Or use multiple file inputs) - its a code that you need to build for your use case - depending on what you feel better with.

**Comment by con322** [comment]
Is there a tutorial or anything on your web tips blog? I see one for multiple file upload using ajax.

I know know to setup the form however bit confused on how to do a for each loop to go through the images and save them to database.

**Comment by kartik-v** [comment]
Usually you can find webtips if available, by clicking the ringing bell icon on the title section of each demo page like the [FileInput Demo Page](http://demos.krajee.com/widget-details/fileinput).

[File Input related webtips can be found here](http://webtips.krajee.com/tag/FileInput/).
