### ISSUE TITLE
problem with utf-8 characters for filename

### ISSUE THREAD

**Issue by asimakos** [kartik-v/yii2-widget-fileinput#146]
I would like to upload a filename with utf-8 characters such as greek, german etc. The upload occurs successfully for both file size and type, unfortunately its filename is being replaced by strange characters. However when english characters for filename are used, there is no problem at all.

Any idea what it might be wrong with utf-8 characters regarding filename? 

Regards for your great source

**Comment by kartik-v** [comment]
Widget uses the plugin's default slug routine in `pluginOptions['slugCallback']` to escape characters that may break HTML. You can override and configure it for your use case. Read about the [slugCallback here](http://plugins.krajee.com/file-input/plugin-options#slugCallback).

**Comment by asimakos** [comment]
I need support for utf-8 characters and not conversion. The filename is successfully stored in the MySQL (Yii2) via string but it's not uploaded successfully due to no support for utf-8. When i try to display it via image tag or create a download link, i got nothing as it can not find with the right utf-8 name (greek, german etc characters). Can you write an example for filename with utf-8 charset using this particular plugin as it would help me a lot! 

This is my first project using Yii2 and i saw that you have got a great collection with Yii2 widgets and definitely your assistance will be convenient to me.

Regards

**Comment by asimakos** [comment]
I found that it actually depends on the server OS file system language settings and not by the widget itself. So i used the following php function in my controller: 

    ```
$file_name=iconv('UTF-8', 'language//TRANSLIT',$model->field);
    
    $file->saveAs('files/'.$file_name);
```

Thanks a lot for your reply. I am thinking to use many more Yii2 widgets from your great colection and of course rely on your assistance.
