### ISSUE TITLE
%252F in delete url

### ISSUE THREAD

**Issue by shoomlix** [kartik-v/yii2-widget-fileinput#148]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-widget-fileinput.
- [ ] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/fileinput).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (fileinput) issue. (Those should be directed to the [plugin issues repo](https://github.com/fileinput/fileinput/search?q=&type=Issues)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set up this plugin by Composer
2. Implement it in code:
`$object[]['key'] = $company->id;
    echo $form->field($model, 'file')->widget(FileInput::class, [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'deleteUrl' => Url::to(['/companies/delete-logo']),
            'initialPreviewConfig' =>  $object,// конфигурация для удаления фотографий,
            'initialPreview' => $company->logo ? Yii::$app->request->pathInfo.$company->logo : '',
            'initialPreviewAsData' => true,
            'fileActionSettings' => [
                // 'initialPreviewShowDelete' => false,
                'showZoom' => false,
                'showRemove' => false,
            ],
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="fas fa-camera-retro"></i>',
            'browseLabel' => Yii::t('ih', 'Выбрать логотип'),
            'maxFileSize' => 15000,
        ],
    ])`
3. Try to press on the delete button on the image and open a browser console. You will see an url with not a normal encoded slash like %2F but you will see this %252F.

## Expected behavior and actual behavior

When I follow those steps, I see 404 error and not a normally encoded slash — %252F.

I was expecting to delete the image and a normally encoded slash — %2F.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- yii2-widget-fileinput version: "dev-master"

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/fileinput)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Update to the latest release of the extension via composer

**Comment by kartik-v** [comment]
If you are still facing the error try setting the [encodeUrl](http://plugins.krajee.com/file-input/plugin-options#encodeUrl) property to `false` within `pluginOptions`.

**Comment by shoomlix** [comment]
> If you are still facing the error try setting the [encodeUrl](http://plugins.krajee.com/file-input/plugin-options#encodeUrl) property to `false` within `pluginOptions`.

Thank you very much, Kartik. I didn't get that error again. Thanks a lot.
