### ISSUE TITLE
Error on composer update

### ISSUE THREAD

**Issue by Sadi01** [kartik-v/yii2-widget-fileinput#149]
## Steps to reproduce the issue

1. composer update

## Expected behavior and actual behavior

When I follow those steps, I see:

  [Composer\DependencyResolver\SolverProblemsException]                        
  Problem 1                                                                    
      - Installation request for kartik-v/yii2-widget-fileinput dev-master ->  
   satisfiable by kartik-v/yii2-widget-fileinput[dev-master].                  
      - kartik-v/yii2-widget-fileinput dev-master requires kartik-v/bootstrap  
  -fileinput ~4.4 -> no matching package found.

I was expecting update packages.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox

Operating System

- [ ] Linux

**Comment by kartik-v** [comment]
Check with latest release.
