### ISSUE TITLE
Composer error extracting archive in a longer filepath (windows)

### ISSUE THREAD

**Issue by alinv04** [kartik-v/yii2-widget-fileinput#15]
[ErrorException]
  ZipArchive::extractTo(c:\Users\.........longer_path.............................../vendor/composer/f6104ef1/kartik-v-bootstrap-fileinput-f95a7e5\examples/This is a long file name to just check how the fileinput plugin can autosize the file caption displayed across device sizes.jpg): failed to open stream: Invalid argument

I had to move the project into a folder closer to the root in order to perform the update

**Comment by kartik-v** [comment]
The examples folder has been moved to a new repo kartik-v/bootstrap-fileinput-samples
