### ISSUE TITLE
Translate fileinput don't work with 'pt-BR' and 'zh-TW'

### ISSUE THREAD

**Issue by RochaXavier** [kartik-v/yii2-widget-fileinput#150]
I try to translate the plugin with yii2 widget, but it doesn't work:
```
    $form->field($model, 'arquivos')->widget(FileInput::className(), [
        'options' => [
            'multiple' => true
        ],
        'language' => 'pt-BR',
        'pluginOptions' => [
            'maxFileCount' => 10
        ]
    ]);
```
When I try with another language it works, only 'pt-BR' and 'zh-TW' don't.

Looking at the network panel, the file is loaded correctly _"/web/assets/d32e62c3/js/locales/pt-BR.js"_ but the script wrinten by widget sets language to "pt" as follows.

```
<script>window.fileinput_66e1ded4 = {"maxFileCount":10,"language":"pt","resizeImage":false,"autoOrientImage":true,"theme":"fas","purifyHtml":true};
</script>
```

Yii version: 2.0.19
Jquery version: 3.3.1
bootstrap-fileinput version: 5.0.3

**Comment by denis-sanches** [comment]
Hi guys!
I'm facing the same problem trying to set up 'pt-BR' language. It appears to be the same related by @RochaXavier.

My app is currently set up with config Yii::$app->language => 'pt-BR' according to [Yii2 Guide - i18n](https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n).

Some tests:
- config `Yii::$app->language => 'pt-BR'`  renders 'en'
- config `Yii::$app->language => 'pt-br'` (which according to the Yii2 guide is incorret)  renders 'pt' (from Portugal not Brazil)
- pass `->widget(FileInput::class, ['language' => 'pt-BR', ...]` still renders 'en'
- pass `->widget(FileInput::class, ['language' => 'pt-br', ...]` renders 'pt' (from Portugal not Brazil)
- pass `->widget(FileInput::class, ['language' => 'pt', ...]` renders 'pt' (from Portugal not Brazil)
- pass `->widget(FileInput::class, ['language' => 'br', ...]` renders 'en'

Is that a bug, or what am I doing wrong?
@RochaXavier, did you find the solution?

Thank you!
