### ISSUE TITLE
Unable to hide the Delete button from image.

### ISSUE THREAD

**Issue by pawansgi92** [kartik-v/yii2-widget-fileinput#158]
Below is the code I am using but unable to hide the delete button in it.

```
echo $form->field($model, 'cause_agent_file')->widget(FileInput::classname(), [
                                'options' => ['accept' => 'image/*', 'multiple' => true],
                                'pluginOptions' => [
                                    'initialPreview' => $initial_preview_image,
                                    'validateInitialCount' => true,
                                    'initialPreviewAsData' => true,
                                    'initialPreviewConfig' => $initial_preview_image_config,
                                    'allowedFileExtensions' => ['png', 'jpg', 'jpeg'],
                                    'maxFileCount' => 5,
                                    'showUpload' => false,
                                    'showRemove' => false,
                                ],
                                    //      'pluginEvents' => []
                            ])->label(false);
```

**Comment by metd** [comment]
'options' => [
                            'multiple' => true,
                            'accept' => 'image/*', 
                            ], 
                            'pluginOptions' => [
                                'showUpload' => false, // disable on form input location.
                                'maxFileCount' => 5,
                                'fileActionSettings' => [
                                    'showUpload' => false, // disable on image preview.
                                    'showRemove' => false,
                                ]
                            ]

look at fileActionSettings.

**Comment by dev3k** [comment]
try 

` 'pluginOptions' => [ 'initialPreviewShowDelete' => false]`

cant find it anywhere in documentation but saw it [here](https://github.com/kartik-v/bootstrap-fileinput/issues/1482)

**Comment by pawansgi92** [comment]
thanks
