### ISSUE TITLE
Custom internationalization

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/yii2-widget-fileinput#16]
I have to customize the internationalization and noticed that this is not possible right now, because of one * char.

```php
// This
// Yii::$app->i18n->translations['fileinput'] = $this->i18n;
// Should be
Yii::$app->i18n->translations['fileinput*'] = $this->i18n;
```

**Comment by kartik-v** [comment]
You need to set the `i18n` property in the FileInput widget if you need to override translations,

**Comment by thejahweh** [comment]
So I cannot override it in the global config file and have to do it on every widget call?

It is documented in the [yii2-documentation](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html) to do it this way:
```php
'i18n' => [
	'translations' => [
		'fileinput' => [
			'class' => 'yii\i18n\PhpMessageSource',
			'sourceLanguage' => 'en-US',
			'basePath' => '@app/messages'
		],
	],
],
```
But this does not work, because it is overwritten in the FileInput-Widget :confused:

**Comment by kartik-v** [comment]
You can try setting widget defaults at a global level using [yii DI](http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html). 

I have reopened the issue if you feel that the above does not resolve.

**Comment by thejahweh** [comment]
Thx that would solve the issue, but i've seen that the expected text is in the `bootstrap-fileinput` JS-translations, which I also don't know how to customize.

The JS-Translation file was just not recognized because I use the widget in a ajax-request and had just registered the asset, which does not involve the translations. Now I have to do it like this:
```php
ob_start();
FileInput::widget(['name' => 'doesntmatter']);
ob_end_clean();
```

But how do I customize the JS-translation files?

**Comment by kartik-v** [comment]
JS translation files are maintained by plugin and not in yii... when you provide a language property to the widget - the translation js file is automatically loaded. You can choose to override each of these messages through the respective plugin's properties (accessible in FIleInput widget via pluginOptions).

Refer the bootstrap-fileinput plugin docs for adding and submitting your [JS translations](http://plugins.krajee.com/file-input#translations) as a pull request.

**Comment by thejahweh** [comment]
How do I change the JS translation directory? I have to give some special translations which are not that common for all upload fields on a website.

I've tried it like this:
```php
\Yii::$container->set('kartik\file\FileInputAsset', [
	'sourcePath' => '@app/messages/fileinput',
]);
```
But then the whole `sourcePath` is changed and I don't want to copy the `fileinput.js` and `fileinput.min.js` over.
