### ISSUE TITLE
Input fields show &hellip; instead of dots

### ISSUE THREAD

**Issue by EvilKarter** [kartik-v/yii2-widget-fileinput#167]
Sorry I don't know if this is a yii2-widget-fileinput issue or bootstrap-fileinput issue.

## Steps to reproduce the issue

1. Create Form with vendor/kartik-v/yii2-widget-fileinput/src/FileInput.php widget
2. use version 5.1.0 or higher of kartik-v/bootstrap-fileinput
3. Set 'language' => 'de' in yii2 config file

## Expected behavior and actual behavior

When I follow those steps, I see the &hellip; in the Input of my widget. 

I was expecting to see the ... like in Version 5.0.9 or lower of kartik-v/bootstrap-fileinput

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox

Libraries

- jQuery version: v3.4.1
- bootstrap-fileinput version: 5.1.0 or Higher
- yii2-widget-fileinput: 1.0.9

## Isolating the problem
I think the problem is that in the local js fils the dots in the msgPlaceholder where replaced with the &hellip; entity
(enh #1577): Use `&hellip;` instead of three dots

**Comment by kartik-v** [comment]
This will be resolved via kartik-v/bootstrap-fileinput#1589

**Comment by EvilKarter** [comment]
nice! Thank you very much! Your yii2 extensions are awesome! I'm really looking forward to yii3
