### ISSUE TITLE
Weird Error 256 in live hosting environment

### ISSUE THREAD

**Issue by newscloud** [kartik-v/yii2-widget-fileinput#17]
I'm getting a weird Error (#256)
An internal server error occurred.
The above error occurred while the Web server was processing your request.
http://screencast.com/t/PB0xxVbth

Removing this line allows the page to load
<?= $form->field($model, 'image')->widget(FileInput::classname(), [
                 'options' => ['accept' => 'image/*'],
             ]);   
              ?>

Works in my local environment on MAMP.

No error appears in Apache log.

Composer self-update and update in live environment.

Any idea?

p.s. this is part of this tutorial series at Tuts+ https://code.tutsplus.com/series/building-your-startup-with-php--cms-742

**Comment by kartik-v** [comment]
It seems some problem with incomplete code/ or invalid install. You can temporarily set YII_DEBUG to true and see the error source in your production instance.

**Comment by skapeyi** [comment]
@newscloud did you find out what the problem was? I have the exact same problem.
