### ISSUE TITLE
purify.js 404 Not Found after update to bootstrap-fileinput release v5.1.2

### ISSUE THREAD

**Issue by xfuturomax** [kartik-v/yii2-widget-fileinput#170]
purify.js was removed from dependent library https://github.com/kartik-v/bootstrap-fileinput/compare/v5.1.2...master.
But it is still required in https://github.com/kartik-v/yii2-widget-fileinput/blob/master/src/FileInput.php#L169

Libraries

- yii2-widget-fileinput version: dev-master, 1.0.x-dev (1.0.9)
- bootstrap-fileinput version: dev-master, 5.1.x-dev (5.1.2)

**Comment by xfuturomax** [comment]
Sorry it will be in version 5.1.3, but you need to pay attention to this issue, I think.

**Comment by kartik-v** [comment]
Fixed via #171
