### ISSUE TITLE
Remove of glyph icons break the icons for bs3

### ISSUE THREAD

**Issue by papppeter** [kartik-v/yii2-widget-fileinput#177]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-fileinput.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/fileinput).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (fileinput) issue. (Those should be directed to the [plugin issues repo](https://github.com/fileinput/fileinput/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. update composer to the latest state
2. it will update kartik-v/bootstrap-fileinput to 5.2.2
3. all icons are gone

## Expected behavior and actual behavior

I should see icons.
I would suggest maybe freeze kartik-v/bootstrap-fileinput to 5.1.*

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version: 3.5.1
- yii2-widget-fileinput version: 1.1.0

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/fileinput)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Set the theme to `gly` in your fileinput widget configuration to use glyphicons with BS3. The project has moved away from BS3 and since v5.x -- its very difficult to add defaults for BS3... now BS v5.x is out and so the project has defaults set to support BS4.x and BS5.x.
