### ISSUE TITLE
Support for Safari browser

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-widget-fileinput#18]
Does this extension support Safari browser? I tried it on Safari 5.1.7, but the upload button didn't appear. There is only a blank button on the rendered page.

**Comment by kartik-v** [comment]
You must [read the pre-requisites for the plugin](http://plugins.krajee.com/file-input#pre-requisites) - it requires the browser to support HTML5 File API which is supported by most modern browsers.

Check your [browser support for File API here](http://caniuse.com/#feat=fileapi).
