### ISSUE TITLE
BS5 is-invalid css error not work

### ISSUE THREAD

**Issue by railton** [kartik-v/yii2-widget-fileinput#181]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-fileinput.
- [ x This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/fileinput).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (fileinput) issue. (Those should be directed to the [plugin issues repo](https://github.com/fileinput/fileinput/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Using bootstrap5 the error css doesn't work, "is-invalid"
```
 <?= $form->field($model, 'csvFile')->widget(FileInput::classname(), [
                                'options' => ['accept' => 'text/csv'],
                                'pluginOptions' => [
                                    'browseClass' => 'btn btn-dark',
                                    'showPreview' => false,
                                    'showCaption' => true,
                                    'showRemove' => true,
                                    'showUpload' => false,
                                    'showCancel' => false
                                ]                            
                            ]); ?>
```

## Expected behavior and actual behavior
Actual code
```
<input readonly="" class="file-caption-name form-control kv-fileinput-caption" placeholder="Selecionar arquivo ..." title="">
```
I was expecting...
```
<input readonly="" class="file-caption-name form-control kv-fileinput-caption is-invalid" placeholder="Selecionar arquivo ..." title="">
```

**Comment by kartik-v** [comment]
It works fine on the tests (the class is-valid is placed when validated successfully). Ensure you have the latest releases.

**Comment by kartik-v** [comment]
It works fine on the tests (the class is-valid is placed when validated successfully). Ensure you have the latest releases. 

> *NOTE:* The Yii2 validation will only work if you are using a simple form based FileInput (without ajax `uploadUrl`) and you must have set the validation rules in your MODEL for the validation of fileinput to work.

**Comment by railton** [comment]
When the input is valid it updates correctly:
```
<input readonly="" class="file-caption-name form-control kv-fileinput-caption **is-valid**" placeholder="Selecionar arquivo ..." title="Usuarios_20210902110424.csv">
```

However, when it is invalid, it updates another input:
```
<input readonly="" class="file-caption-name form-control kv-fileinput-caption" placeholder="Selecionar arquivo ..." title="">
<input type="file" id="importform-csvfile" class="light btn-light **is-invalid**" name="ImportForm[csvFile]" accept="text/csv" aria-required="true" aria-invalid="true" data-krajee-fileinput="fileinput_7f8e9b5a">
```

**Comment by kartik-v** [comment]
Cannot reproduce this.  To test this [check this test demo](https://demos.krajee.com/site/test). The model attribute includes a file validation to allow only *.jpg* extensions - try selecting a different file extension to test the invalid check.
