### ISSUE TITLE
In Update form

### ISSUE THREAD

**Issue by randaelayan** [kartik-v/yii2-widget-fileinput#19]
Hi, 

Thank you for your module, it's been such a huge help.

I am new to yii, and I generated my models and crud using gii.

I installed your module and included the widget and worked like charm in the Create form.

Also in update form, but not being able to figure out how to get the field value "the images source" to the preview of the image.

Thanks in advance.

**Comment by kartik-v** [comment]
You need to do this in your Controller action that renders the widget for update.

Check these web tips

#### For form based uploads

- [Upload file in Yii 2 using FileInput widget](http://webtips.krajee.com/upload-file-yii-2-using-fileinput-widget)
- [Advanced upload using Yii2 FileInput widget](http://webtips.krajee.com/advanced-upload-using-yii2-fileinput-widget)

#### For ajax uploads 
This is a generic approach not specifically for yii - but you can adapt it.
- [Ajax based file uploads using FileInput plugin](http://webtips.krajee.com/ajax-based-file-uploads-using-fileinput-plugin)
