### ISSUE TITLE
How to display a confirm box upon file delete icon click?

### ISSUE THREAD

**Issue by vsmelarkod** [kartik-v/yii2-widget-fileinput#24]
Dear Kartik,

How to program a confirmation dialog for the user when they click on the delete icon on the preview of an existing image / file? This is my current code in controller - 

echo $form->field($model, 'images[]')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => true],
        'pluginOptions' => [
            'allowedFileExtensions' => ['jpg', 'gif', 'png'],
            'initialPreview' => [
                Html::img("/images/moon.jpg", ['class' => 'file-preview-image', 'alt' => 'The Moon', 'title' => 'The Moon']),
                Html::img(Yii::$app->params['imagesUrl'] . "default.png", ['class' => 'file-preview-image', 'alt' => 'The Earth', 'title' => 'The Earth']),
            ],
            'initialPreviewConfig' => [
                [
                    'caption' => 'The Moon',
                    'url' => Url::toRoute(['page/removefile', 'file' => 'moon.png']),
                ],
                [
                    'caption' => 'Default',
                    'url' => Url::toRoute(['page/removefile', 'file' => 'default.png']),
                ],
            ],
        ]
    ]);

**Comment by kartik-v** [comment]
Get the updated plugin code and refer the [ajax demo scenario # 8](http://plugins.krajee.com/file-input-ajax-demo/8).

**Comment by gomonkey** [comment]
the [ajax demo scenario # 8.](http://plugins.krajee.com/file-input-ajax-demo/8) have some bug.
If you press cancel, it send anyway the request for delete the file.

**Comment by kartik-v** [comment]
Get the updated code. Demo has been updated as well.

**Comment by gomonkey** [comment]
Thank you kartik,
pay attention when you click cancel button, it lose "btn btn-k" classes

**Comment by kartik-v** [comment]
Resolved with the latest commit and fix for kartik-v/bootstrap-fileinput#1119.
