### ISSUE TITLE
Cross frame scripting

### ISSUE THREAD

**Issue by hscstudio** [kartik-v/yii2-widget-fileinput#25]
I use your fileInput widget, and then my auditor tester this.. it found Cross frame scripting..

Auditor use HP Web inspect tools,, can You verified?

**Comment by kartik-v** [comment]
Not sure what - you may need to understand details on what is proposed and where its reported in your developed page?

Check for example [this SFO question](http://stackoverflow.com/questions/27782673/client-cross-frame-scripting-attack-resolution)

**Comment by kartik-v** [comment]
In case you do find any details - do post them here and this issue can be opened if needed. Closing this issue as of now.
