### ISSUE TITLE
InitialCaption not works when is not a image fileinput

### ISSUE THREAD

**Issue by leandrogehlen** [kartik-v/yii2-widget-fileinput#26]
When  the property `initialPreview` is not set, the `initialCaption` not works

**Comment by kartik-v** [comment]
It was intended to be that way. Will record an enhancement for this.

**Comment by kartik-v** [comment]
This will be resolved via kartik-v/bootstrap-fileinput#245.

**Comment by leandrogehlen** [comment]
thanks
