### ISSUE TITLE
Amazon S3 support

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-fileinput#27]
Hi,

Thanks for contributing the plugin to the community!!!

Does this plugin support upload to Amazon S3?
Does this functionality will be supported in the near future?

**Comment by kartik-v** [comment]
This is not currently supported. Please feel free to add a PR if you want it faster.

**Comment by kartik-v** [comment]
This is not currently supported.

The plugin does provide you with methods and events to call your own APIs or webservices.

Please feel free to add a PR if you want it inbuilt.

**Comment by kartik-v** [comment]
Answered in kartik-v/bootstrap-fileinput#197.
