### ISSUE TITLE
CSS conflict in partial view

### ISSUE THREAD

**Issue by vsmelarkod** [kartik-v/yii2-widget-fileinput#32]
Hi Kartik,

I am using the fileinput widget on yii2 '_form' (partial view) which I am loading using 'render'. All the functionalities work. However, the CSS is breaking in the 'create' and 'update' pages only. The rest of the web application looks fine. I inspected the page in Chrome and found another Bootstrap.css is being loaded from the assets in the create and update pages - 

link href="/rgcf/web/assets/c097cb88/css/bootstrap.css" rel="stylesheet"

when I delete the link tag from the 'inspect element', the website looks normal again. Have you encountered this issue? any way I can fix this? Thank you for your help.

**Comment by kartik-v** [comment]
Check your AssetBundle dependencies (you may want to check the Yii docs). One way to address your issue is to unset the problem bundle which is duplicating the CSS in your view for the use case.
