### ISSUE TITLE
Translation is not passed to the bootstrap-fileinput

### ISSUE THREAD

**Issue by thejahweh** [kartik-v/yii2-widget-fileinput#33]
Nothing is translated by default, because the `language` is not passed to the bootstrap-fileinput. The translation file is loaded but the bootstrap-fileinput language is set to default.

A workaround is to set it manually at every fileinput
```php
<?= $form->field($article, 'file')->widget(FileInput::className(), [
	'pluginOptions' => [
		'language' => Yii::$app->language
	],
]) ?>
```

To fix it, I think it should be set at the widget `init()`
```php
if (!isset($this->pluginOptions['language'])) $this->pluginOptions['language'] = $this->language;
```

**Comment by kartik-v** [comment]
Resolved via d96e605.
