### ISSUE TITLE
Different view with same options

### ISSUE THREAD

**Issue by Boco10** [kartik-v/yii2-widget-fileinput#34]
Hello. 

Why i get different view with the same options?

<a href="http://tinypic.com?ref=6jiydd" target="_blank"><img src="http://i57.tinypic.com/6jiydd.png" border="0" alt="Image and video hosting by TinyPic"></a>

<code>div class="row padding_both_side">
        <?= $form->field($model, "pictures[]")->widget(FileInput::classname(), [
                                    'options'=>[
                                        'multiple'=>true,
                                        'accept' => 'image/*',
                                    ],
                                    'pluginOptions' => [
                                        'previewFileType' => 'any',
                                        'showUpload' => false,
                                        'allowedFileExtensions'=>['jpg','gif','png'],
                                        'maxFileCount' => 5
                                    ]
                                ]);?>
    </div>

    <?php 

    echo FileInput::widget([
    'name' => 'attachment_48[]',
    'options'=>[
        'multiple'=>true
    ],
    'pluginOptions' => [
        'uploadUrl' => Url::to(['/site/file-upload']),
        'uploadExtraData' => [
            'album_id' => 20,
            'cat_id' => 'Nature'
        ],
        'maxFileCount' => 10
    ]
]);</code>

**Comment by Boco10** [comment]
Basicly the question is why it renders the input without the multiple option?
![image](https://cloud.githubusercontent.com/assets/9821606/8652727/80788604-2980-11e5-969a-1033bdabd443.png)

Above is the bad which i generated from :
<code> <?= $form->field($model, "pictures[]")->widget(FileInput::classname(), [
                                    'options'=>[
                                        'multiple'=>true,
                                        'accept' => 'image/*',
                                    ],
                                    'pluginOptions' => [
                                        'previewFileType' => 'any',
                                        'showRemove' => false,
                                        'showUpload' => false,
                                        'allowedFileExtensions'=>['jpg','gif','png'],
                                        'maxFileCount' => 5
                                    ]
                                ]);?></code>


This is from your example:

<input type="file" id="w12" class="file-loading" name="attachment_48" multiple data-krajee-fileinput="fileinput_fa57d48f">

So the multiple option is missing. What's wrong?

**Comment by kartik-v** [comment]
Not sure of why you are facing the issue. But the example you shared from the widget docs is correct and you can check it.

One thing that I see is that you have `uploadUrl` set and that means you are using AJAX mode for submission and not the native HTML file input that can be submitted via normal form. If you are intending to use the latter you should not combine the modes. You may want to [read the plugin documentation and the usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes). You should not be using `uploadUrl` and form submission together.
