### ISSUE TITLE
Reinitialize FileInput components

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-widget-fileinput#35]
I have several FileInput components in a page and initially they work well. However, after ajax refresh, most of them are broken. I tried to reinitialize them:

```
$('input.file-upload').each(function() {
    $(this).fileinput(eval($(this).attr('data-krajee-fileinput')));               
});
```

but got a weird result:
![alt text](http://rei.evetest.com/fileinput.png)

How to reinitialize FileInput correctly?

**Comment by kartik-v** [comment]
Use new `destroy` method of the plugin and reinitialize.
