### ISSUE TITLE
fileinput did not show

### ISSUE THREAD

**Issue by ReverseFlash28** [kartik-v/yii2-widget-fileinput#38]
please help me. fileinput didnot display

![screen shot 2015-08-06 at 5 40 12 pm](https://cloud.githubusercontent.com/assets/8644115/9108751/e1ca2864-3c62-11e5-92ca-c8fde3c06777.png)

**Comment by kartik-v** [comment]
Debug your code and javascript console (on browser) for other javascript errors (that may be caused by other plugins).

**Comment by joshuadiezmo** [comment]
![screen shot 2015-08-06 at 6 21 47 pm](https://cloud.githubusercontent.com/assets/8644115/9109413/1264fd00-3c68-11e5-966e-86e402fc196d.png)
no error

**Comment by kartik-v** [comment]
Cannot reproduce your issue. Seems some issue specific to your environment:

- seems more like some javascript issue - either jquery not loaded 
- you have a conflict with other javascript - 
- or a browser specific issue where the browser has blocked javascript OR you have a wrong browser

So you need to debug and see above. Check if the [demo sites](http://plugins.krajee.com/file-input) work fine on your browser and work from there

**Comment by joshuadiezmo** [comment]
yes. it works fine in demo

**Comment by joshuadiezmo** [comment]
thanks. i found out that jasny-bootstrap.js is the reason why my fileinput have error.
