### ISSUE TITLE
Usage incomplete

### ISSUE THREAD

**Issue by lorinczelod** [kartik-v/yii2-widget-fileinput#41]
Why don't put this code snippet too in README.md -> Usage?
For me didn't work the upload without this.
```
<?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'] // important
    ]); ?>
```
Otherwise good widget :)

**Comment by kartik-v** [comment]
Yes the above is needed for all native file inputs and will update the Readme.

But it is not needed if you are using the widget in AJAX mode.
