### ISSUE TITLE
massive of files in russian and english

### ISSUE THREAD

**Issue by nelli7** [kartik-v/yii2-widget-fileinput#42]
Hello! I was able to upload files with russian letters, but if I upload with russian and english letters at the same time, it is not uploading everything. If files in english it is uploading all files.
In a form I have:
echo $form->field($files, 'file[]')->widget(FileInput::classname(), [
    'options' => ['multiple' => true,'id'=>"input-fcount-2",'class'=>'file-loading'],
   
    'pluginOptions' => [
'slugCallback' => new JsExpression('function(filename) {
return filename;
}'
),
],

            ]);
In js file I have
 slugCallback: function(filename) {
         return filename.replace('', '_');
     },

But it is working only for one files, others are not uploaded..

**Comment by kartik-v** [comment]
Duplicate to #59... update to latest plugin code...
