### ISSUE TITLE
Wrong file uploaded with multiple files and image validation error. 

### ISSUE THREAD

**Issue by momone83** [kartik-v/yii2-widget-fileinput#43]
![schermata 2015-09-09 alle 12 28 15](https://cloud.githubusercontent.com/assets/6953666/9759585/51d4f3a0-56ee-11e5-982c-c89e5f4188bb.png)

Hi. I configured the widget (the last available version managed by composer) to accept only images with specific dimensions. If I select the files as in the image above and one of these is not valid because its dimensions are not right (in this case the panoramic photo), the widget works well and shows me the error message. Now, if I started the upload, the video file (the first) in the preview area is ignored and the widget uploads the wrong file instead. If I delete the wrong file from the preview area and I start the upload, the first video file is ignored in this case too. I think this is an index management error. I don't know well the widget's code logic, but I suppose that the image size validation does not exclude the index of the wrong file when it find one. The widget shows the animated progress bar also for the wrong file during the upload and so it seems that the file is uploaded. Can you tell me if I forgot to add any configuration or to handle some event or if this is a bug instead? 
I hope I'm making myself clear.
Thanks.

Below the code:

FileInput::widget([
            'id' => 'media-files-input',
            'name' => 'mediaFiles[]',
            'options'=>[
                'multiple'=>true,
            ],
            'pluginOptions' => [
                'uploadUrl' => Url::to(['/artwork-media/file-upload']),
                'uploadExtraData' => [
                    'idArtwork' => $artwork->idArtwork
                ],
                'maxFileCount' => 5,
                'showCaption' => false,
                'browseClass' => 'btn btn-success',
                'browseIcon' => '<i class="glyphicon glyphicon-folder-open"></i> ',
                'browseLabel' =>  'Select Media',
                'allowedFileExtensions' => ['jpg','mp4','mp3'],
                'maxFileSize' => 40000,
                'maxImageWidth' => 6000,
                'maxImageHeight' => 6000,
                'minImageWidth' => 600,
                'minImageHeight' => 600,
                'dropZoneTitle' => 'Trascina i files qui...',
                'showCaption' => false,
                'showRemove' => true,
                'showUpload' => true,
                'uploadClass' => 'btn btn-info',
                'removeClass' => 'btn btn-danger',
                'removeIcon' => '<i class="glyphicon glyphicon-trash"></i>',
                'layoutTemplates' => [
                    'actionUpload' => ''
                ]
            ]
        ]);

**Comment by kartik-v** [comment]
Will need to check this use case - could you provide a JS fiddle for this?
