### ISSUE TITLE
Cannot Delete Files Uploaded Via AJAX

### ISSUE THREAD

**Issue by TNChalise** [kartik-v/yii2-widget-fileinput#45]
### How can I setup my response so that I will be able to delete the file I have Just Uploaded ? [@kartik-v ]
I have been trying to delete files that are uploaded by ajax, but it seems this is not working for me.
The image attached here, is the response that I have sent from server upon successful upload.
- Images are rendered well, but the delete option is not working.

![upload-response](https://cloud.githubusercontent.com/assets/4486063/10121963/b076daa0-6525-11e5-9ba2-d966c4153279.png)

## My View File is:
```php

    // Usage with ActiveForm and model
    echo $form->field($documents, 'document_path')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => true],
        'pluginOptions' => [
            'uploadUrl' => Url::to(['documents']),
            'uploadExtraData' => [
                'mysecret' => 'secret',
            ],
            'maxFileCount' => 10
        ]
    ]);

```

**Comment by kartik-v** [comment]
Duplicate to kartik-v/bootstrap-fileinput#457. Refer [the comment](https://github.com/kartik-v/bootstrap-fileinput/issues/457?_pjax=%23js-repo-pjax-container#issuecomment-143532542).
