### ISSUE TITLE
Drag An Drop Broken

### ISSUE THREAD

**Issue by osCMattiFinn** [kartik-v/yii2-widget-fileinput#47]
Drag and drop appears to be broken.

The widget displays "Drag & drop files here …"

When I try to drag a file to it, the CSS changes as expected, however the file being dragged displays a crossed circle icon and won't drop.

What's up?

**Comment by kartik-v** [comment]
Cannot reproduce. You may want to update to latest release, clear your old webserver runtime assets, and browser cache and retry.
