### ISSUE TITLE
Language error

### ISSUE THREAD

**Issue by osCMattiFinn** [kartik-v/yii2-widget-fileinput#48]
This throws the following error:

```php
Calling unknown method: kartik\file\FileInputAsset::addLanguage()
```

**Comment by osCMattiFinn** [comment]
So, I commented the offending line and now get this:

```javascript	
jQuery('#product-product_image').fileinput(fileinput_749acade);
```

**Comment by osCMattiFinn** [comment]
I found the problem is that your extension does not update dependencies correctly.

**Comment by kartik-v** [comment]
Cannot reproduce the issue nor has it been faced or reported. You need to check your app and extension install and update extensions via `composer`
