### ISSUE TITLE
How to show button delete of initPreview image??

### ISSUE THREAD

**Issue by dieuhd** [kartik-v/yii2-widget-fileinput#49]
I set 'initialPreviewShowDelete'  => true, but delete button of initPreview not show.
Please help me.

**Comment by kartik-v** [comment]
Read docs and demos in detail at http://plugins.krajee.com/file-input.

You must set the `initialPreviewConfig` and a valid `initialPreviewConfig['url']` that will point to the delete server action. 

Refer [ajax demo 3 for an example](http://plugins.krajee.com/file-input-ajax-demo/3).
