### ISSUE TITLE
Is this widget complete ?

### ISSUE THREAD

**Issue by brunofunny** [kartik-v/yii2-widget-fileinput#50]
Well I'm trying to do something simple change "browseLabel" using the "pluginOptions" parameter, but what was my surprise when I saw that $this->pluginOptions just get the 'showPreview' parameter.

Is this widget fully implemented with bootstrap-file-input ?

**Comment by kartik-v** [comment]
Yes the widget fully utilizes and allows you to implement the `bootstrap-fileinput` plugin features.
