### ISSUE TITLE
The message file for category 'fileinput' does not exist

### ISSUE THREAD

**Issue by uagrace** [kartik-v/yii2-widget-fileinput#51]
I get an error message:
"The message file for category 'fileinput' does not exist: 
..\site\vendor\kartik-v\yii2-krajee-base/messages/ru-RU/fileinput.php 
Fallback file does not exist as well: 
..\site\vendor\kartik-v\yii2-krajee-base/messages/ru/fileinput.php"

**Comment by uagrace** [comment]
To solve this problem need add to widget config:
'i18n' => [
        'class' => 'yii\i18n\PhpMessageSource',
        'basePath' => '@fileinput/messages',
],

**Comment by kartik-v** [comment]
This bug is resolved via kartik-v/yii2-krajee-base#48 and [this commit](https://github.com/kartik-v/yii2-krajee-base/commit/2432d126772d7755301731ed364b3e988eb8dcfe)... will tag the release soon once I get a few confirmations.

**Comment by uagrace** [comment]
Thanks!

**Comment by sinergycode** [comment]
Hi kartik-v i have the same bug. 
Where i need to put this code:
'i18n' => [
    'class' => 'yii\i18n\PhpMessageSource',
    'basePath' => '@fileinput/messages',
], 

?

**Comment by kartik-v** [comment]
It seems you are using a LANGUAGE/LOCALE for which message file does not exist in this plugin. You just need to submit a PULL REQUEST for your LANGUAGE file in this repo - that I can merge.

**Comment by sinergycode** [comment]
I need to put this code:
'i18n' => [
'class' => 'yii\i18n\PhpMessageSource',
'basePath' => '',
],
in git console?
