### ISSUE TITLE
issue with Yii2 CSRF cookie validation failing; "Unable to verify your data submission"

### ISSUE THREAD

**Issue by Hommer101** [kartik-v/yii2-widget-fileinput#6]
I kept getting 400 "Unable to verify your data submission." errors from the controller where the upload heads. I've verified that the CSRF token is in the header as well as at the start of the form definition as a hidden input but still no luck.

I managed to get it working again with correct CSRF token validation by adding the following option to the widget:
```
'options' => [
    'uploadExtraData'=> new \yii\web\JsExpression('_csrf:yii.getCsrfToken()'),
],
```

Strangely before my addition, the request did contain a CSRF cookie, but its value wasn't valid; it failed the check in `\yii\base\Security validateData()`.

**Comment by kartik-v** [comment]
Cannot replicate this currently. Closing this. You can raise a new issue if you do find any leads on this.

**Comment by mtangoo** [comment]
I found same issue and had to increase size of the following in php.ini
post_max_size = 200M
upload_max_filesize = 180M

Note former MUST be larger than latter to avoid future issues

**Comment by lennartvdd** [comment]
Had the same problem and in my case also, the problem only occurred when uploading files larger than the php.ini's `upload_max_filesize` value. This looks more like a core framework bug to me.
