### ISSUE TITLE
Invalid file extention

### ISSUE THREAD

**Issue by stepancher** [kartik-v/yii2-widget-fileinput#60]
in require "kartik-v/bootstrap-fileinput": "~4.2" , but if i use "kartik-v/bootstrap-fileinput": "@dev"
this call bug. "Invalid file extention" on all files. Bug in bootstrap-fileinput or bundle with widget. If that normal - Ok, if that a bug please fix it. Good day

**Comment by kartik-v** [comment]
Not sure... cannot reproduce your use case. You may need to check the installation and see what plugin version you have installed and if it is the latest.
