### ISSUE TITLE
Hashed javascript variable loading in head fails using PJAX forms

### ISSUE THREAD

**Issue by ncramer** [kartik-v/yii2-widget-fileinput#61]
I'm using PJAX to run through a list of enrollment forms.

Registering hashed JS variables at POS_HEAD causes them to be undefined when the page is not fully refreshed. Moving them to POS_LOAD fixes the issue elsewhere, but in the case of this widget, this breaks other JS loaded in POS_HEAD, and I haven't been able to fully resolve the changes required.

Here's a similar issue in Yii core MaskedInput that was recently resolved:
https://github.com/yiisoft/yii2/issues/10029

Any chance this can be fixed/supported?

**Comment by kartik-v** [comment]
Use `renderPjax` method to render widgets via pjax. Using POS_READY will break the actual purpose of why the variable is registered in POS_HEAD. The variable registration allows you to especially use same settings  for advanced cases like tabular forms and perform other JavaScript operations when multiple widgets are present or when u wish to dynamically render the widget again using same settings via JS.
