### ISSUE TITLE
Delete button on initialPreview doesn't shows.

### ISSUE THREAD

**Issue by whocaresk** [kartik-v/yii2-widget-fileinput#64]
I've dived through billions of refers to bootstrap plugin documentation (in yii2 widget branch), but still can't make it work. I even can't find any valid and working examples to get, what i'm doing wrong (yii2-fileinput docs has very little info about configuring this widget).
I'm trying to make widget be able to delete initialPreview images. I'm setted up initialPreviewConfig and still it doesn't show any delete buttons. Here is my View code: 
```php
$img = '/yii2shop/backend/web/img/407_1.jpg';
    \kartik\file\FileInput::widget([
        'name' => 'name',
        'options'=>[
            'multiple'=>true
        ],
        'pluginOptions' => [
            'initialPreviewShowDelete' => true,
            'allowedFileExtensions' => ['jpg', 'gif', 'png'],
            'overwriteInitial' => false,
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => true,
            'initialPreview' => [
                '<img src="'.$img.'" class="file-preview-image">',
            ],
            'initialCaption' => '407_1.jpg',
            'initialPreviewConfig' => [
                'caption' => '407_1.jpg',
                'url' => \yii\helpers\Url::toRoute(['image/delete']),
            ],
        ]
    ])
```
Please, help me. I have a sense, that it just doesn't recognize 'initialPreviewConfig' option.

**Comment by whocaresk** [comment]
I'm really stupid.
```php
$img = '/yii2shop/backend/web/img/407_1.jpg';
    \kartik\file\FileInput::widget([
        'name' => 'name',
        'options'=>[
            'multiple'=>true
        ],
        'pluginOptions' => [
            'initialPreviewShowDelete' => true,
            'allowedFileExtensions' => ['jpg', 'gif', 'png'],
            'overwriteInitial' => false,
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => true,
            'initialPreview' => [
                '<img src="'.$img.'" class="file-preview-image">',
            ],
            'initialCaption' => '407_1.jpg',
            'initialPreviewConfig' => [
                [
                      'caption' => '407_1.jpg',
                       'url' => \yii\helpers\Url::toRoute(['image/delete']),
                ],
            ],
        ]
    ])
```
This way it works just perfect. initialPreviewConfig MUST contain arrays with data, not just data.
For more clear code i suggest to introduce this:
```php
 'initialPreviewConfig' => [
               'config' => [
                      'caption' => '407_1.jpg',
                       'url' => \yii\helpers\Url::toRoute(['image/delete']),
                ],

```

**Comment by rupsk1607** [comment]
In my case i tried a lot but delete button is not showing.
im i write this in 
echo $form->field($model, 'imageFiles[]')->widget(FileInput::classname(), [
            'options' => ['multiple' => true, ],            
            'pluginOptions' => [ 
                    'initialPreviewShowDelete' => true,
                    'overwriteInitial'=>false,
                    'initialPreview'=>$allimage,
                    'initialCaption'=>"The Moon and the Earth",
                    'initialPreviewConfig' => [
                        ['caption' => 'Moon.jpg', 'size' => '873727'],
                        ['caption' => 'Earth.jpg', 'size' => '1287883'],
                    ],   
                'showPreview' => true,
                'showCaption' => true,
                'showRemove' => true,
                'showUpload' => true,   
            ],

        ]);
than it show delete button on first image.


  $allimage[] = '';
    if (!$model->isNewRecord) 
	{		 
		$imagesData = ArrayHelper::map(RoomImages::find()->where(['roomTypeId' => $model->roomTypeId])->all(),'roomImagesId','imageName');
		 
		foreach($imagesData as $iKey=>$iVal)
		{ 
         $allimage[] = Html::img('@web/uploads/'.$iVal,  ['class'=>'file-preview-image img-thumbnail']);
          
        } 
         
	} ?>
       </div>
       <?php echo $form->field($model, 'imageFiles[]')->widget(FileInput::classname(), [
            'options' => ['multiple' => true, ],            
            'pluginOptions' => [ 
                     'initialPreviewShowDelete' => true,
                      'overwriteInitial'=>false,
                    'initialPreview'=>$allimage,
                     'initialPreviewConfig' => [
                            [
                                'caption' => "People-1.jpg",
                                'width' => "120px",
                                'url' => "/site/file-delete",
                                'key' => 1,
                            ],
            ],
                    'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => true,   
            ],

        ]);
	 ?>
