### ISSUE TITLE
multiple does not work

### ISSUE THREAD

**Issue by masiha68** [kartik-v/yii2-widget-fileinput#65]
Hi
Multiple does not work for me !

[echo $form->field($memorysImages, 'image')->widget(\kartik\file\FileInput::classname(), [

        'language' => 'fa',
        'options' => ['multiple' => true, 'accept' => 'image/*'],
        'pluginOptions' => [

            'showPreview' => true,
            'showCaption' => false,
            'showRemove' => true,
            'showUpload' => true,
            'maxFileCount' => 100,

            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' =>  'select images',
        'uploadUrl' => \yii\helpers\Url::to(['memorys/addimage']),
        'uploadExtraData' => [

        ],

        ]
        ])->label(false)->fileInput(['class'=>'remind-option']);](url)

**Comment by kartik-v** [comment]
You need to understand a bit about file inputs being read by PHP (use array naming convention for attribute).

[Refer this webtip on how you should configure this](http://webtips.krajee.com/read-html5-multiple-file-input-php/)
