### ISSUE TITLE
Canvas-to-blob is not register when needed

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/yii2-widget-fileinput#66]
I was getting error **fileinput.js:703 Uncaught TypeError: Cannot read property '$errorContainer' of undefined**, so I debugged code and noticed that widget does not register CanvasBlobAsset, despite resizeImage is true.

**View:**
```
use kartik\widgets\FileInput;
use yii\helpers\Url;
echo FileInput::widget([
    'name' => 'input-pl[]',
    'pluginOptions' => [
        'uploadUrl' => Url::to(['/announcement/upload-image']),
        'resizeImage' => true,
        'maxImageWidth' => 640,
     ],
]);
```
Is it a bug or I am missing something?

**Comment by kartik-v** [comment]
You may want to read [docs for fileinput widget settings](http://demos.krajee.com/widget-details/fileinput#settings). You must set the `resizeImages` property at the widget level to true for this to happen.

**Comment by koxu1996** [comment]
@kartik-v After latest releases, using code from your comment I am getting error: `Uncaught TypeError: Cannot read property '$errorContainer' of undefined`

**Comment by temirfe** [comment]
in docs it says we have to load CanvasBlobAsset, and how do we load that asset? There is no such asset in vendor src folder exept PiExifAsset.
