### ISSUE TITLE
How to change icon

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-widget-fileinput#67]
I not see in documentation how to change this icon
Or how to disable to 'upload' or 'delete' in thumbnail not show up
![untitled-1](https://cloud.githubusercontent.com/assets/8703419/13593965/ff9e1b24-e532-11e5-9e0a-db8cdc4851c7.jpg)

**Comment by kartik-v** [comment]
Read [about layoutTemplates in the plugin docs](http://plugins.krajee.com/file-input#option-layouttemplates). 

You can change `actions`, `footer`, or `actionUpload` or `actionDelete` depending on your need...

**Comment by adiramardiani** [comment]
Icon delete in footer not affected when change icon, for example :
```php
'pluginOptions' => [ // Plugin options of the Kartik's FileInput widget 
			'removeIcon' => '<span class="icon">delete</span> ',
		]
```

in documentation :

actionDelete : {removeIcon}: the icon for the remove button. Will be replaced with the removeIcon set within fileActionSettings.

But is not affected, please check

Thanks

**Comment by kartik-v** [comment]
You need to closely read and follow what the documentation says:

> `actionDelete` : `{removeIcon}`: the icon for the remove button. Will be replaced with the removeIcon set within fileActionSettings.

So you must set [`removeIcon` within fileActionSettings](http://plugins.krajee.com/file-input#option-fileactionsettings).

Which in Yii fileinput widget will translate to 

```php
'pluginOptions' => [ // Plugin options of the Kartik's FileInput widget 
    'fileActionSettings' => [
        'removeIcon' => '<span class="icon">delete</span> ',
    ]
]
```
