### ISSUE TITLE
Multiple file input instances renders incorrectly.

### ISSUE THREAD

**Issue by akaSStalkALEX** [kartik-v/yii2-widget-fileinput#68]
This is my view code: 
```
echo '<label class="control-label">One</label>';
echo FileInput::widget([
    'model' => new UploadForm(),
    'attribute' => 'file',
]);
echo '<label class="control-label">Two</label>';
echo FileInput::widget([
    'model' => new UploadForm(),
    'attribute' => 'file',
]);
```

I see this on the page. Second input is spinning infinitely.
![default](https://cloud.githubusercontent.com/assets/2943154/13735370/65fc87c0-e9ca-11e5-8a2b-a5fa68379722.PNG)

As I understand problem is in same attribute for both widgets.

**Comment by kartik-v** [comment]
Yes it will not work with your code (you may want to cross check usage of input widgets in Yii) as it will break the HTML and as well as any such jquery plugin. 

You need to have unique HTML identifiers for each input element for plugins that you are initializing via jquery.

**Comment by akaSStalkALEX** [comment]
Ok, how can I get validation on form whether file was uploaded in case of without model usage?

**Comment by kartik-v** [comment]
You can still use model - but ensure your identifiers are unique or use array naming convention for attributes (like in tabular data) - so that your model validations work. Check yii docs for details.

**Comment by akaSStalkALEX** [comment]
I tried to give 'file[]' as attribute name for both of them, but it also not working.

**Comment by kartik-v** [comment]
As I said read yii docs... this is not related to file input... something like...

```php
for ($i = 1; $i < 5; $i++) {
    echo $form->field($model, "[$i]file")->widget(FileInput::classname(), [
        // your widget settings
    ]);
}
```

**Comment by akaSStalkALEX** [comment]
Okay, now I got it, thank you for your time. Also I will check docs again.

**Comment by vc7deo** [comment]
hi kartik,

i can use

```
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
<?= $form->field($model, 'file')->widget(\dosamigos\fileinput\FileInput::className())->label('Application Form');?>
    <?php ActiveForm::end(); ?>

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
<?= $form->field($model, 'file')->widget(\dosamigos\fileinput\FileInput::className())->label('Application Form');?>
    <?php ActiveForm::end(); ?>
```

multiple times but i replace it with yours i got above problem

**Comment by kartik-v** [comment]
As I mentioned you need to have an unique id for the yii2 FileInput widget to render the plugin correctly. 
Please ensure that in your code.

**Comment by vc7deo** [comment]
@kartik-v ,
perfect now its working. Thank you!!
