### ISSUE TITLE
Setting up document\excel preview

### ISSUE THREAD

**Issue by ApXaHgheJI** [kartik-v/yii2-widget-fileinput#78]
Good day, sorry for open an ISSUE - but can't find any where how to display after save the document or other types of files.

` <?php
                        $previewDocument = null;

                        if (!empty($model->getProductDocuments()->all())) {
                            $previewDocument = [
                                'initialPreview' => null,
                                'initialPreviewAsData' => true,
                                'allowedExtensions' => ['doc', 'xdoc', 'pdf', 'xlsx', 'xls'],
                            ];
                            foreach ($model->getProductDocuments()->all() as $document) {
                                $ext = pathinfo($document->document_path, PATHINFO_EXTENSION);
                                switch ($ext) {
                                    default :
                                        $previewDocument['initialPreview'][] = [str_replace('admin.', '', \yii\helpers\Url::home(true)) . ltrim($document->document_path, '/')];
                                        break;
                                }

                            }
                        }

                        // With model & without ActiveForm
                        echo '<label class="control-label">' . Yii::t('app', 'Add Attachments') . '</label>';
                        echo \kartik\file\FileInput::widget([
                            'model' => $model,
                            'attribute' => 'document[]',
                            'options' => [
                                'multiple' => true,
                            ],
                            'pluginOptions' => $previewDocument,
                        ]);
                        ?>`

Right now there is usecase ( because I was try to change the InitialPreview template..
but no way...

Best regards.

**Comment by ApXaHgheJI** [comment]
Images are displayed ok, and that is all.

**Comment by kartik-v** [comment]
The display of content is nothing to do with the plugin and has to be natively supported by browsers.., and only html, text, images, video (html5 support), audio (html5 support), pdf and other content natively supported by browsers for preview can be viewed. If you find a method to preview these documents on the browser natively without other controls do let know...
