### ISSUE TITLE
JS Error: "formdata is not defined" when set maxFileSize

### ISSUE THREAD

**Issue by relaxpor** [kartik-v/yii2-widget-fileinput#8]
when set maxFileSize plugin options and upload the file that exceeds its limit,
the preview show document with red warning icon.
But no any error alert text was shown.

the browser console log showing "formdata is not defined"
on the fileinput.js script line number 1242.

Please advise.

**Comment by kartik-v** [comment]
Upgrade to latest release of bootstrap-fileinput plugin for these bug fixes
