### ISSUE TITLE
Initial Preview remove buttons do not work

### ISSUE THREAD

**Issue by cornernote** [kartik-v/yii2-widget-fileinput#80]
The initial preview works perfectly, except the small red remove buttons don't do anything when you click them.  In order to remove you have to remove all the files.

Your demo suffers from this same issue.

I did notice that after you select a new file the remove buttons on the existing files begins to work.

**Comment by cornernote** [comment]
I also noticed that if I upload a new file, then remove the initial file, nothing gets uploaded.

**Comment by kartik-v** [comment]
Cannot understand your query. Share a JS Fiddle or point to a link with what is expected.

**Comment by cornernote** [comment]
Sorry, I should have used some images to help explain.

When you use the Initial Preview feature, the remove buttons don't work:

![clipboard01](https://cloud.githubusercontent.com/assets/51875/17641505/40cde3b2-6162-11e6-9017-4da94eb10c32.jpg)

However after you upload a new image, the remove buttons on the initial preview files begin to work:

![clipboard01](https://cloud.githubusercontent.com/assets/51875/17641522/b06ca73a-6162-11e6-8e84-b3a20274f37b.jpg)

**Comment by cornernote** [comment]
My second issue is that after removing the initial preview images and uploading a new image, the $_FILES array will contain a `UPLOAD_ERR_NO_FILE` error.

![2016-08-13_1433](https://cloud.githubusercontent.com/assets/51875/17641535/3963fce6-6163-11e6-8c8d-2f7921062122.png)

**Comment by kartik-v** [comment]
On your first query... The delete button for initial preview works... Cross check with the [plugin demos page and advanced demo example # 1](http://plugins.krajee.com/file-advanced-usage-demo#advanced-example-1)...

**Comment by cornernote** [comment]
It works there, wondering the difference when using the activeform example on the demo page. Will check details when I'm back in front of a keyboard.

**Comment by cornernote** [comment]
Had a quick look, I think it's because `deleteUrl` isn't defined.

I'll play with it some more.  Maybe if that's setup properly the other issue will go away.

**Comment by nerd3717** [comment]
I had same problem. thank you very much cornernote. Documentation is made in single (looong) page and it's uncomfortably to read
