### ISSUE TITLE
Uploading files automatically on drag and drop

### ISSUE THREAD

**Issue by orkhanalizade** [kartik-v/yii2-widget-fileinput#81]
Is it possible to upload files automatically on drag and drop without pressing upload button under the image?

**Comment by kartik-v** [comment]
Read the plugin [documentation](http://plugins.krajee.com/), [plugin events](http://plugins.krajee.com/file-input#events), and [plugin demos](http://plugins.krajee.com/file-input/demo).

Your use case is [covered in this demo example](http://plugins.krajee.com/file-input-ajax-demo/6).
