### ISSUE TITLE
modify $_FILES name

### ISSUE THREAD

**Issue by kunx-edu** [kartik-v/yii2-widget-fileinput#82]
I want change the file object's name.
but I cant.
I modify name property but it is not work!

> <?php echo $form->field($model, 'image')->widget(\kartik\file\FileInput::classname(), [
    'name'=>'Filedata',
    'options' => ['multiple' => true],
    'pluginOptions' => [
        'uploadUrl' => yii\helpers\Url::to(['s-upload']),
        'uploadExtraData' => [
            'album_id' => 20,
            'cat_id' => 'Nature'
        ],
        'maxFileCount' => 10
    ]
]);?>

**Comment by kartik-v** [comment]
You need to read yii documentation. Names for input widgets based on model attributes are auto generated by yii. The `name` property above will only work for NON MODEL based widgets. For model based widgets ... You can control it with `options['name']` property ... however the model validation rules and model loading may break if you change it...

**Comment by kunx-edu** [comment]
great!

at yesterday , i guess this like your words,now I am sure!

thankyou very much!

发自我的 iPhone
