### ISSUE TITLE
How add one more button to yii2-widget-fileinput?

### ISSUE THREAD

**Issue by aminkt** [kartik-v/yii2-widget-fileinput#83]
Hi.
In my app i use this widget and now i need one more button to perform some actions in my app for every picture uploaded before.
My current code is like this:

```
$allPics = \common\models\Picture::getPictures($album->id);
$images = [];
$imagesOptions = [];
if($allPics){
    foreach ($allPics as $pic){
         $key = $pic->id;
         $url = Url::to(['set-pic-status', 'id'=>$key, 'pid'=>$model->id, 'do'=>'remove']);
         $images[] = Yii::$app->urlManagerFront->createAbsoluteUrl(['image/index', 'id'=>$pic->id, 'width'=>300, 'height'=>300]);
         $imagesOptions[] = ['caption' => $pic->name, 'size' => $pic->size , 'url'=>$url, 'key'=>$key];
    }
} 
echo FileInput::widget([
     'name' => 'pic',
     'language'=>'fa',
     'options'=>[
         'multiple'=>true
     ],
     'pluginOptions' => [
         'uploadUrl' => Url::to(['pic-upload', 'id'=>$model->id]),
         'initialPreview'=>$images,
         'initialPreviewAsData'=>true,
         'initialCaption'=>"تصاویر محصول",
         'initialPreviewConfig' => $imagesOptions,
         'overwriteInitial'=>false,
         'maxFileSize'=>2800,
     ]
]);
```

And result of top code is: 
![image](https://cloud.githubusercontent.com/assets/14914854/17648693/e596d4b8-6233-11e6-8f22-6aadffac8dbd.png)

Now i need add one more button near remove button to send some data to server and set selected picture as cover or change status of picture in db.

How can i do that?
I think this item is available.  true?
Thanks a lot for your help. :)

@kartik-v

**Comment by midcore-nam** [comment]
did you figure this out? i've spent too many hours trying to figure this out and it comes to the point i wanna shoot myself.

**Comment by midcore-nam** [comment]
nvm...figured it out.

**Comment by kartik-v** [comment]
Read documentation. You can use the [otherActionButtons property](http://plugins.krajee.com/file-input#option-otheractionbuttons) to set your additional action buttons markup for each thumbnail.
