### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by hdushku** [kartik-v/yii2-widget-fileinput#84]
When I try to update the image I get this error:

move_uploaded_file(/uploads/NWgef02XR0OW-xXsXh0Zn8LtyhPE1SOq.jpg): failed to open stream: No such file or directory

I have an uploads directory in root homepage with 777 rights.

**Comment by kartik-v** [comment]
This is not related to the extension... more to do with handling file inputs in Yii .. cross check yii docs.
