### ISSUE TITLE
filebatchuploadcomplete event duplicate

### ISSUE THREAD

**Issue by notgosu** [kartik-v/yii2-widget-fileinput#9]
Hi,

after declaring 'filebatchuploadcomplete' event handler and upload any photo amount few time i see duplicates.
The way i am declaring event handler
``
$(document).on('filebatchuploadcomplete', '#storeproduct-images', function(event, files, extra) {
    console.log('File batch upload complete');
});
``

I am using ajax upload.

**Comment by kartik-v** [comment]
Test with the latest release of the bootstrap-fileinput extension.

**Comment by notgosu** [comment]
bootstrap-fileinput v4.1.5 have the same behavior

**Comment by kartik-v** [comment]
As mentioned you must upgrade to the latest release of bootstrap-fileinput (v4.1.6).

**Comment by notgosu** [comment]
Sorry, just yesterday composer did not update the bootstrap-fileinput to latest v4.1.6.
Today it updated successfully. It seems that problem is fixed, thanks!
