### ISSUE TITLE
File upload with image preview not working in frontend

### ISSUE THREAD

**Issue by kishor10d** [kartik-v/yii2-widget-fileinput#92]
In backend, the \kartik\file\FileInput is working like charm. But in my frontend, it not working. It showing normal file upload control there. I customize the css in frontend.

_The rendered HTML is as follows:_
```
<input type="file" id="w0" class="file-loading" name="primaryimage[image][]" multiple="" data-krajee-fileinput="fileinput_f44733d1">
<!--[if lt IE 10]><br><div class="alert alert-warning"><strong>Note:</strong> Your browser does not support file preview and multiple file upload. Try an alternative or more recent browser to access these features.</div><script>document.getElementById("w0").className.replace(/\bfile-loading\b/,"");;</script><![endif]-->
```

Why this thing is appearing? Any fix for this issue?

**Comment by yumi-vv** [comment]
I am experiencing it too. Last 2 days ago it was working then suddenly the whole page is not working when the fileinput widget in it. Is there a fix for this? thanks
