### ISSUE TITLE
Android : Plugin not supported

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-widget-fileinput#93]
I tried to upload a pdf on your demo page while on my android mobile
But the preview says "plugin not supported"
Is it my phone ?
Do I need to install something on my phone ?
Is it something else ?

**Comment by kartik-v** [comment]
Android browsers do not have PDF preview enabled by default - the latest versions of the bootstrap-fileinput plugin use `pdf.js` library for such situations. This is controlled via [`usePdfRenderer`](http://plugins.krajee.com/file-input/plugin-options#usePdfRenderer) setting which defaults to iOS and Android devices. Refer the [PDF Preview Demo](http://plugins.krajee.com/file-preview-management-demo#preview-pdf).
