### ISSUE TITLE
Previews duplication after uploading images

### ISSUE THREAD

**Issue by ANDRU19** [kartik-v/yii2-widget-fileinput#94]
When i'm trying to upload one image with ajax and return a valid response, file input shows two previews of one uploaded images. In the case, if to upload 2 or more images then no duplication.

**Comment by wilmer737** [comment]
I have the same issue. Two thumbnail previews are shown after an ajax call to upload the file. Has there been any investigation into this?

**Comment by kartik-v** [comment]
This issue is duplicate to kartik-v/bootstrap-fileinput#890 and resolved via latest release on master branch of the code.
