### ISSUE TITLE
Is it possible to upload image with caption like Facebook?

### ISSUE THREAD

**Issue by bhattaxay** [kartik-v/yii2-widget-fileinput#97]
I want to upload multiple image with drag and drop functionality and also want to add caption below image while uploading an image. Is it possible using fileInput? I have followed your demo but no such option like as per my requirement.  [http://demos.krajee.com/widget-details/fileinput](url)

**Comment by kartik-v** [comment]
Go through the docs and check the file input plugin demos page instead. You will find lot more examples there.

An example of caption upload is described in [this ajax demo scenario # 7](http://plugins.krajee.com/file-input-ajax-demo/7).

**Comment by bhattaxay** [comment]
okk thanks

**Comment by bhattaxay** [comment]
I have followed your scenario, but it's not load the widget in my view. Follow the link: [http://stackoverflow.com/questions/41951038/image-with-caption-file-input-widget-not-loading-in-view](url)
