### ISSUE TITLE
How do I can remove the label above input file form?

### ISSUE THREAD

**Issue by kepingatp** [kartik-v/yii2-widget-fileinput#98]
Thanks for this awesome ext :)
How do I can remove the label above input file form?

![fi](https://cloud.githubusercontent.com/assets/20182181/22493190/25c6b464-e861-11e6-829f-672cb9aa4a91.PNG)
From the example above, I want to remove / hide the "File" label.

And I think, that label based on `model` name.

This is the code I use:
`<?=
    $form->field($model, 'file')->widget(FileInput::classname(), [
        'options' => [
            'accept' => 'doc/*', 'file/*',
            'enableLabel' => false,
        ],
        'pluginOptions' => [
            'allowedFileExtensions' => ['csv', 'xls', 'xlsx'],
            'showUpload' => FALSE,
            'showPreview' => FALSE,
        ]
    ]);
    ?>`

How the way I can do that?
Thanks

**Comment by kartik-v** [comment]
This is more a yii active form and field configuration.

~~~
echo $form->field($model, 'file')->label(false)->widget(...);
~~~
